const members = [{
  id: 1,
  isStudent: true,
  name: '이승만',
  gradeNumber: 1,
  classNumber: 1,
  checkedToady: undefined,
}, {
  id: 2,
  isStudent: true,
  name: '윤보선',
  gradeNumber: 1,
  classNumber: 1,
  checkedToady: undefined,
}, {
  id: 3,
  isStudent: true,
  name: '박정희',
  gradeNumber: 1,
  classNumber: 1,
  checkedToady: undefined,
}, {
  id: 4,
  isStudent: true,
  name: '최규하',
  gradeNumber: 1,
  classNumber: 1,
  checkedToady: undefined,
},
{
  id: 5,
  isStudent: true,
  name: '전두환',
  gradeNumber: 2,
  classNumber: 1,
  checkedToady: undefined,
},
{
  id: 6,
  isStudent: true,
  name: '노태우',
  gradeNumber: 2,
  classNumber: 1,
  checkedToady: undefined,
},
{
  id: 7,
  isStudent: true,
  name: '김영삼',
  gradeNumber: 3,
  classNumber: 1,
  checkedToady: undefined,
},
{
  id: 8,
  isStudent: true,
  name: '김대중',
  gradeNumber: 3,
  classNumber: 1,
  checkedToady: undefined,
},
{
  id: 9,
  isStudent: true,
  name: '노무현',
  gradeNumber: 3,
  classNumber: 1,
  checkedToady: undefined,
},
{
  id: 10,
  isStudent: true,
  name: '이명박',
  gradeNumber: 3,
  classNumber: 1,
  checkedToady: undefined,
},
{
  id: 11,
  isStudent: true,
  name: '박근혜',
  gradeNumber: 3,
  classNumber: 1,
  checkedToady: undefined,
},
];

export default members;
